export const STATS = [
  { value: "40+",  label: "Câu lạc bộ"    },
  { value: "5K+",  label: "Thành viên"     },
  { value: "120+", label: "Sự kiện/năm"   },
    
];

export const CLUBS = [
  {
    emoji: "💻",
    color: "#1C3F94",
    name: "CLB Lập Trình FPT",
    abbr: "FPT Coder",
    categoryCode: "IT",
    desc: "Nơi hội tụ những lập trình viên đam mê công nghệ, cùng nhau xây dựng dự án thực tế.",
    members: 320,
    tag: "Công nghệ",
    recruiting: true,
  },
  {
    emoji: "🎨",
    color: "#9B2335",
    name: "CLB Thiết Kế Sáng Tạo",
    abbr: "FPT Design",
    categoryCode: "Design",
    desc: "Khơi dậy năng lực sáng tạo qua UI/UX, đồ họa, và nghệ thuật số hiện đại.",
    members: 185,
    tag: "Thiết kế",
    recruiting: false,
  },
  {
    emoji: "🎤",
    color: "#5C3D99",
    name: "CLB Kỹ Năng Mềm",
    abbr: "FPT Skill",
    categoryCode: "Skill",
    desc: "Rèn luyện thuyết trình, lãnh đạo, giao tiếp và xây dựng tư duy phát triển.",
    members: 240,
    tag: "Kỹ năng",
    recruiting: true,
  },
  {
    emoji: "🤖",
    color: "#0A7A6B",
    name: "CLB Trí Tuệ Nhân Tạo",
    abbr: "FPT AI Club",
    categoryCode: "AI",
    desc: "Nghiên cứu và ứng dụng Machine Learning, Deep Learning vào các bài toán thực tế.",
    members: 150,
    tag: "AI & Data",
    recruiting: true,
  },
  {
    emoji: "🏆",
    color: "#D4770A",
    name: "CLB Khởi Nghiệp",
    abbr: "FPT StartUp",
    categoryCode: "Biz",
    desc: "Ươm mầm ý tưởng kinh doanh, kết nối mentor và cộng đồng startup năng động.",
    members: 210,
    tag: "Business",
    recruiting: false,
  },
  {
    emoji: "🌍",
    color: "#1A6B3C",
    name: "CLB Tiếng Anh",
    abbr: "FPT English",
    categoryCode: "Lang",
    desc: "Nâng cao kỹ năng tiếng Anh toàn diện qua debate, storytelling và giao lưu quốc tế.",
    members: 280,
    tag: "Ngôn ngữ",
    recruiting: true,
  },
  {
    emoji: "📸",
    color: "#7A2D8A",
    name: "CLB Nhiếp Ảnh",
    abbr: "FPT Lens",
    categoryCode: "Art",
    desc: "Khai phá ngôn ngữ hình ảnh, từ chụp chân dung đến nhiếp ảnh đường phố đô thị.",
    members: 130,
    tag: "Nghệ thuật",
    recruiting: false,
  },
  {
    emoji: "⚽",
    color: "#1A6095",
    name: "CLB Thể Thao",
    abbr: "FPT Sport",
    categoryCode: "Sport",
    desc: "Giao lưu và thi đấu các môn thể thao: bóng đá, cầu lông, bơi lội và nhiều hơn nữa.",
    members: 400,
    tag: "Thể thao",
    recruiting: false,
  },
];

export const EVENTS = [
  {
    emoji: "💻",
    color: "#1C3F94",
    title: "Hackathon FPT 2025 – Build The Future",
    club: "FPT Coder",
    date: "15/6/2025",
    time: "08:00",
    venue: "Hội trường A",
    venueDetail: "Đại học FPT Hà Nội",
    currentParticipants: 180,
    maxParticipants: 200,
    desc: "48 giờ lập trình marathon, giải thưởng lên đến 50 triệu đồng cho đội chiến thắng.",
    longDesc: "Đây là cơ hội tuyệt vời để sinh viên giao lưu, học hỏi và phát triển kỹ năng trong môi trường thực tế. Sự kiện mở cửa cho tất cả sinh viên FPTU.",
    badge: "Đăng ký mở",
    badgeType: "open",
  },
  {
    emoji: "🎨",
    color: "#9B2335",
    title: "Workshop: UI/UX Design với Figma 2025",
    club: "FPT Design",
    date: "22/6/2025",
    time: "14:00",
    venue: "Phòng Lab 3",
    venueDetail: "Đại học FPT Hà Nội",
    currentParticipants: 45,
    maxParticipants: 80,
    desc: "Học kỹ năng thiết kế giao diện chuyên nghiệp từ chuyên gia hàng đầu trong ngành.",
    longDesc: "Workshop thực hành trực tiếp trên Figma, từ wireframe đến prototype hoàn chỉnh. Phù hợp với cả người mới bắt đầu lẫn những ai muốn nâng cao kỹ năng thiết kế.",
    badge: "Sắp diễn ra",
    badgeType: "upcoming",
  },
  {
    emoji: "🤖",
    color: "#0A7A6B",
    title: "Toạ đàm: AI & Tương Lai Nghề Nghiệp",
    club: "FPT AI Club",
    date: "28/6/2025",
    time: "09:00",
    venue: "Hội trường B",
    venueDetail: "Đại học FPT TP.HCM",
    currentParticipants: 90,
    maxParticipants: 150,
    desc: "Chuyên gia chia sẻ xu hướng AI và cách sinh viên chuẩn bị cho kỷ nguyên tự động hoá.",
    longDesc: "Sự kiện quy tụ các chuyên gia hàng đầu trong lĩnh vực AI để chia sẻ về xu hướng công nghệ và định hướng nghề nghiệp. Đây là cơ hội kết nối trực tiếp với các doanh nghiệp công nghệ lớn.",
    badge: "Sắp diễn ra",
    badgeType: "upcoming",
  },
  {
    emoji: "🌍",
    color: "#1A6B3C",
    title: "FPT English Debate Championship 2025",
    club: "FPT English",
    date: "5/7/2025",
    time: "08:30",
    venue: "Sân khấu chính",
    venueDetail: "Đại học FPT Đà Nẵng",
    currentParticipants: 120,
    maxParticipants: 120,
    desc: "Giải tranh biện tiếng Anh thường niên với sự tham gia của 20+ đội thi từ các trường.",
    longDesc: "Cuộc thi tranh biện tiếng Anh quy mô lớn nhất năm, quy tụ các đội thi xuất sắc từ nhiều trường đại học. Ban giám khảo gồm các chuyên gia ngôn ngữ và doanh nhân quốc tế.",
    badge: "Hết chỗ",
    badgeType: "full",
  },
  {
    emoji: "🏆",
    color: "#D4770A",
    title: "Startup Pitch Night – Season 3",
    club: "FPT StartUp",
    date: "12/7/2025",
    time: "18:00",
    venue: "Innovation Hub",
    venueDetail: "Đại học FPT Hà Nội",
    currentParticipants: 60,
    maxParticipants: 100,
    desc: "Đêm gọi vốn với sự có mặt của 15 nhà đầu tư và mentor đến từ hệ sinh thái FPT.",
    longDesc: "Sân chơi dành cho các startup trẻ có cơ hội trình bày ý tưởng trực tiếp trước các nhà đầu tư và mentor giàu kinh nghiệm. Giải thưởng lên đến 100 triệu đồng cho ý tưởng xuất sắc nhất.",
    badge: "Đăng ký mở",
    badgeType: "open",
  },
];
