-- Migration: Automatic Event Report Schema & Filtered Unique Index
-- Version: V2026072508

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'reportSource')
BEGIN
    ALTER TABLE dbo.EventReport ADD reportSource VARCHAR(20) NOT NULL CONSTRAINT DF_EventReport_reportSource DEFAULT 'MANUAL_UPLOAD';
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'autoGeneratedAt')
BEGIN
    ALTER TABLE dbo.EventReport ADD autoGeneratedAt DATETIME2 NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'generatorVersion')
BEGIN
    ALTER TABLE dbo.EventReport ADD generatorVersion VARCHAR(20) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'templateVersion')
BEGIN
    ALTER TABLE dbo.EventReport ADD templateVersion VARCHAR(20) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'reportDataHash')
BEGIN
    ALTER TABLE dbo.EventReport ADD reportDataHash VARCHAR(64) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'reportSnapshotJson')
BEGIN
    ALTER TABLE dbo.EventReport ADD reportSnapshotJson NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'leaderCommentsJson')
BEGIN
    ALTER TABLE dbo.EventReport ADD leaderCommentsJson NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'pdfHash')
BEGIN
    ALTER TABLE dbo.EventReport ADD pdfHash VARCHAR(64) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.EventReport') AND name = 'version')
BEGIN
    ALTER TABLE dbo.EventReport ADD version BIGINT NOT NULL CONSTRAINT DF_EventReport_version DEFAULT 0;
END

-- Unique active report index per event
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_EventReport_Event_Active' AND object_id = OBJECT_ID('dbo.EventReport'))
BEGIN
    CREATE UNIQUE INDEX UX_EventReport_Event_Active
    ON dbo.EventReport(eventID)
    WHERE isDeleted = 0;
END
