export const STATS = [
  { value: "40+",  label: "Câu lạc bộ"    },
  { value: "5K+",  label: "Thành viên"     },
  { value: "120+", label: "Sự kiện/năm"   },
  { value: "12",   label: "Năm hoạt động" },
];

export const CLUBS = [
  {
    emoji: "💻",
    color: "#1C3F94",
    name: "CLB Lập Trình FPT",
    abbr: "FPT Coder",
    desc: "Nơi hội tụ những lập trình viên đam mê công nghệ, cùng nhau xây dựng dự án thực tế.",
    members: 320,
    tag: "Công nghệ",
  },
  {
    emoji: "🎨",
    color: "#9B2335",
    name: "CLB Thiết Kế Sáng Tạo",
    abbr: "FPT Design",
    desc: "Khơi dậy năng lực sáng tạo qua UI/UX, đồ họa, và nghệ thuật số hiện đại.",
    members: 185,
    tag: "Thiết kế",
  },
  {
    emoji: "🎤",
    color: "#5C3D99",
    name: "CLB Kỹ Năng Mềm",
    abbr: "FPT Skill",
    desc: "Rèn luyện thuyết trình, lãnh đạo, giao tiếp và xây dựng tư duy phát triển.",
    members: 240,
    tag: "Kỹ năng",
  },
  {
    emoji: "🤖",
    color: "#0A7A6B",
    name: "CLB Trí Tuệ Nhân Tạo",
    abbr: "FPT AI Club",
    desc: "Nghiên cứu và ứng dụng Machine Learning, Deep Learning vào các bài toán thực tế.",
    members: 150,
    tag: "AI & Data",
  },
  {
    emoji: "🏆",
    color: "#D4770A",
    name: "CLB Khởi Nghiệp",
    abbr: "FPT StartUp",
    desc: "Ươm mầm ý tưởng kinh doanh, kết nối mentor và cộng đồng startup năng động.",
    members: 210,
    tag: "Business",
  },
  {
    emoji: "🌍",
    color: "#1A6B3C",
    name: "CLB Tiếng Anh",
    abbr: "FPT English",
    desc: "Nâng cao kỹ năng tiếng Anh toàn diện qua debate, storytelling và giao lưu quốc tế.",
    members: 280,
    tag: "Ngôn ngữ",
  },
  {
    emoji: "📸",
    color: "#7A2D8A",
    name: "CLB Nhiếp Ảnh",
    abbr: "FPT Lens",
    desc: "Khai phá ngôn ngữ hình ảnh, từ chụp chân dung đến nhiếp ảnh đường phố đô thị.",
    members: 130,
    tag: "Nghệ thuật",
  },
  {
    emoji: "⚽",
    color: "#1A6095",
    name: "CLB Thể Thao",
    abbr: "FPT Sport",
    desc: "Giao lưu và thi đấu các môn thể thao: bóng đá, cầu lông, bơi lội và nhiều hơn nữa.",
    members: 400,
    tag: "Thể thao",
  },
];

export const EVENTS = [
  {
    day: "15",
    month: "Th6",
    title: "Hackathon FPT 2025 – Build The Future",
    club: "FPT Coder",
    time: "08:00 – 20:00",
    location: "Hội trường A – FPT Hà Nội",
    desc: "48 giờ lập trình marathon, giải thưởng lên đến 50 triệu đồng cho đội chiến thắng.",
    badge: "Đăng ký mở",
    badgeType: "open",
  },
  {
    day: "22",
    month: "Th6",
    title: "Workshop: UI/UX Design với Figma 2025",
    club: "FPT Design",
    time: "14:00 – 17:30",
    location: "Phòng Lab 3 – FPT Hà Nội",
    desc: "Học kỹ năng thiết kế giao diện chuyên nghiệp từ chuyên gia hàng đầu trong ngành.",
    badge: "Sắp diễn ra",
    badgeType: "upcoming",
  },
  {
    day: "28",
    month: "Th6",
    title: "Toạ đàm: AI & Tương Lai Nghề Nghiệp",
    club: "FPT AI Club",
    time: "09:00 – 12:00",
    location: "Hội trường B – FPT TP.HCM",
    desc: "Chuyên gia chia sẻ xu hướng AI và cách sinh viên chuẩn bị cho kỷ nguyên tự động hoá.",
    badge: "Sắp diễn ra",
    badgeType: "upcoming",
  },
  {
    day: "05",
    month: "Th7",
    title: "FPT English Debate Championship 2025",
    club: "FPT English",
    time: "08:30 – 17:00",
    location: "Sân khấu chính – FPT Đà Nẵng",
    desc: "Giải tranh biện tiếng Anh thường niên với sự tham gia của 20+ đội thi từ các trường.",
    badge: "Hết chỗ",
    badgeType: "full",
  },
  {
    day: "12",
    month: "Th7",
    title: "Startup Pitch Night – Season 3",
    club: "FPT StartUp",
    time: "18:00 – 21:00",
    location: "Innovation Hub – FPT Hà Nội",
    desc: "Đêm gọi vốn với sự có mặt của 15 nhà đầu tư và mentor đến từ hệ sinh thái FPT.",
    badge: "Đăng ký mở",
    badgeType: "open",
  },
];
