package com.fptu.fcms.exception;

public enum ApiErrorCode {
    BAD_REQUEST,
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    EVENT_STATE_INVALID,
    REGISTRATION_CLOSED,
    TYPE_NOT_ALLOWED,
    CAPACITY_FULL,
    QUOTA_FULL,
    ALREADY_CHECKED_IN,
    TICKET_INVALID,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INVALID_IMAGE,
    IMAGE_UPLOAD_FAILED,
    IMAGE_DELETE_FAILED,
    INTERNAL_ERROR
}
